### ISSUE TITLE
Top Operator Tag + Support missing new operator.

### ISSUE THREAD

**Issue by 125Magnus** [Aceship/AN-EN-Tags#100]
I just did a Top Operator Recruitment with Support combination. Did 9 hours, and immediately used the red ticket. I got Magallan - I double checked the tags, and Magallan is neither in Support or Top Operator.

**Comment by erasemee** [comment]
Yup, I just rolled a Top operator Support tag; receiving Magellan, who was not even listed on the calc

**Comment by BryghtShadow** [comment]
Magellan added in the CC4 Lead Seal update, according to Gamepress: "New Operators will be added to the Recruitment Pool as part of the upcoming CC4 Lead Seal." https://gamepress.gg/arknights/news/arknights-guide-cc4-lead-seal-recruitment-updates

> **Tag List:** Top Operator, Ranged, Supporter, Support, Slow, DPS
> **Guarantee Combos to get this Operator:** Top Operator + Supporter, Top Operator + Slow, Top Operator + Ranged + DPS + Support

**Comment by Aceship** [comment]
should be fixed now
