### ISSUE TITLE
Bubble's 2nd infrastructure skill info mismatch (18 capacity in game vs 16 listed in aceship)

### ISSUE THREAD

**Issue by CaiMarkJayson** [Aceship/AN-EN-Tags#101]
Operator Bubble's 2nd infrastructure skill "Bigger is Better!" is listed as giving operators productivity bonus based on 18 increased capacity limit in game, in aceship however it is listed as 16 instead. (EN Server)
![1](https://user-images.githubusercontent.com/61429145/126011685-028e2a80-d64d-4cbd-a84c-0ccc4e28bf31.png)
![2](https://user-images.githubusercontent.com/61429145/126011845-67432929-4bda-431d-afa4-915cc1c432fb.png)

also a variable that has escaped in the 2nd screenshot

**Comment by Abkaal** [comment]
AFAIK Aceship's version is accurate for CN

**Comment by CaiMarkJayson** [comment]
Doesn't Aceship have the ability to change descriptions based on the server

**Comment by Abkaal** [comment]
Probably. Depends on how is this data acquired. If it's where I think it is #109 fixes it

**Comment by Aceship** [comment]
>
>
> Doesn't Aceship have the ability to change descriptions based on the server

tbh en data isnt used in infrastructure skill
server based stuff only works on recruitment



> 
> 
> Probably. Depends on how is this data acquired. If it's where I think it is #109 fixes it

that one is technically cn version translation so currently its alright 

>
>
> also a variable that has escaped in the 2nd screenshot

about this one, i think 1 of the past fix already fixes it


just to say, operator details page technically mostly follow cn version 
except operator voiceline and story which follows en version if it exist 

(last time tried to add en server support directly, it broke too much so i haven't touched that again)

**Comment by CaiMarkJayson** [comment]
Then I guess the best fix for this would probably be having a simple note somewhere that says "All data and information is taken from the CN version, EN details may differ slightly."
