### ISSUE TITLE
Operator comparing JS error

### ISSUE THREAD

**Issue by Hunman** [Aceship/AN-EN-Tags#103]
Selecting more than one operator throws a JS error
`db.atkType` is an object, you likely wanted to search in `db.atkType.parts`
![image](https://user-images.githubusercontent.com/7405480/128567890-20524aaa-57a2-4a40-804f-b54ef3a6e98c.png)

Removing the first operator displays the next one's stats
![image](https://user-images.githubusercontent.com/7405480/128567806-99cd8861-3f4f-4103-b3bb-ec6b29b10b5e.png)
![image](https://user-images.githubusercontent.com/7405480/128567955-1ef75b68-76c7-40ce-9174-d655490fa9b4.png)

Full backtrace:
```
Uncaught TypeError: db.atkType.find is not a function
    at akcompare2.js:529
    at Array.forEach (<anonymous>)
    at getProcessedTexts (akcompare2.js:504)
    at RefreshValues (akcompare2.js:290)
    at RefreshSlots (akcompare2.js:209)
    at deleteOp (akcompare2.js:394)
    at HTMLAnchorElement.onclick (VM4065 akhrcompare2.html:1)
```

**Comment by Aceship** [comment]
should be fixed in c1573bc0869430cadf9a3a3e0dd6de3e43105b3b
