### ISSUE TITLE
[Suggestion] Use expanded navbar for lg size screens.

### ISSUE THREAD

**Issue by Airgetfrog** [Aceship/AN-EN-Tags#105]
Currently collapsed navbar is used for screen sizes under 1200px. This behavior is inconvenient for those using the site on vertically rotated monitors as it introduces another click to open the navbar. Using the collapsed navbar only for md and lower screens would fix this issue. Perhaps only navbar items after Information (Elite Materials, Guide, etc.) or region/language settings can be collapsed instead for lg size.

**Comment by Aceship** [comment]
if i understand it right, it should look like this by default on smaller screen size ?
![image](https://user-images.githubusercontent.com/5337323/129277808-5a832cb0-4615-4716-bde4-1ec583179b41.png)

currently i made it like that after what you suggest, try check if i make its right or not
d9f23317a730689bf9acb355a5c7efc175ba1052

**Comment by Airgetfrog** [comment]
Sorry, I meant to keep using the full (non-hamburger-style) menu at medium screen sizes, since there is enough space for all buttons with small modification, like removing the "Arknights Toolbox" title. Currently users using the site on vertical monitor or in a smaller window need an extra click to open the menu even though it is completely unnecessary. Quick mockup below:

![image](https://user-images.githubusercontent.com/29678823/129335217-d8d1f9c6-f950-4f65-85c5-b52f5d5690e6.png)

Also, current implementation is broken and shows full navbar with permanently expanded items on 1200px and does nothing for other widths.

**Comment by Aceship** [comment]
> Also, current implementation is broken and shows full navbar with permanently expanded items on 1200px and does nothing for other widths.

well i thought you wanted this since it allows you 1 less button press

>Sorry, I meant to keep using the full (non-hamburger-style) menu at medium screen sizes

changed it now to only change to hamburger style only with lower than lg ( 991px )
smaller than that still go hamburger style
need to move some of the page tho

**Comment by Aceship** [comment]
i guess its okay now ?

**Comment by Airgetfrog** [comment]
Looks great, thanks for the work!
