### ISSUE TITLE
[Advice] Change the Google Analytics id to your own

### ISSUE THREAD

**Issue by graueneko** [Aceship/AN-EN-Tags#14]
Glad to see your version getting so many new users, congrats!

Recently I review the Google Analytics statistics for [graueneko/aktools-old](https://github.com/graueneko/aktools-old), and find that the number of your user is growing. I think you can change the GA id to your own, to know better how wonderful your work is.

Many pages integrate the GA id in `<head>`, after you've registered one, simply replace this id, e.g.: https://github.com/Aceship/AN-EN-Tags/blob/3b381c38bcf8eae6defedb2205758ad42916c08a/akhr.html#L23 
... and many other pages.

I'm not bothered at all, but I think owning your own statistic data is good for you.

**Comment by Aceship** [comment]
Thanks for the info!
tbh idk that google analytics existed, gonna change it to mine now

**Comment by Aceship** [comment]
i think i've changed it now, but idk how to check if the google analytics actually works or not

**Comment by graueneko** [comment]
This is about how to use the GA dashboard, goto https://analytics.google.com/ and switch the account(on top-left), you can view the real time and history data. 

You can also create some filter or do anything, it's very easy, just read the docs or google it :D

I think this issue can now be closed.
