### ISSUE TITLE
Plz update the recruitment!

### ISSUE THREAD

**Issue by Qqsang794** [Aceship/AN-EN-Tags#148]
The 2.5 anniversary of Arknights Global has updated the recruitment & added Ceobe, Leizi & Purestream! 
Thank you!

**Comment by Qqsang794** [comment]
Thanks!

**Comment by Qqsang794** [comment]
Leizi combo tag is missing the caster class. Just checked on aceship

**Comment by SynfulChaot** [comment]
This issue actually still exists.  The Pull Request has not yet been merged.

**Comment by SynfulChaot** [comment]
This now *is* fixed.
