### ISSUE TITLE
Material Images Not Found

### ISSUE THREAD

**Issue by bbattas** [Aceship/AN-EN-Tags#151]
The images for the materials all seem to be lost or nonexistent.  They all show up everywhere as   
![image](https://user-images.githubusercontent.com/54590188/190013695-f02be0e5-b386-4227-b1ec-37d1d5566a57.png)
And if you open the image file in a new tab or window you get a 404 error.

**Comment by Aceship** [comment]
i think it was fixed in [a0968b9](https://github.com/Aceship/AN-EN-Tags/commit/a0968b9b4d18b7011917b734aea798bc324b4af3)
