### ISSUE TITLE
Sora operator missed from tags recruit search

### ISSUE THREAD

**Issue by the-Arioch** [Aceship/AN-EN-Tags#17]
![Screenshot_20200304-012431](https://user-images.githubusercontent.com/937774/75825847-40748d80-5db7-11ea-814f-185f3c289d1d.jpg)

**Comment by Aceship** [comment]
I don't think you can get sora from tag recruitment
![Screenshot_20200304-055724424](https://user-images.githubusercontent.com/5337323/75827854-17ff8a00-5ddd-11ea-9d49-12e382440a77.png)

can you check the list on en server on this part ?

**Comment by Aceship** [comment]
![image](https://user-images.githubusercontent.com/5337323/75828841-572eda80-5ddf-11ea-9e91-91109e8ac619.png)
yeah seems you cant get sora from tags recruit in en too
