### ISSUE TITLE
akhrelite: choosing CN operators only changes portrait

### ISSUE THREAD

**Issue by arthus-leroy** [Aceship/AN-EN-Tags#21]
1) Choosing a CN-exclusive operator (up to Ch'en currently, Spot is concerned even though being EN too) only changes the portrait regardless of the server chosen.
2) The names given to the items are the non-official names and should be changed.

![aceship_error_cnOp_in_en](https://user-images.githubusercontent.com/46849630/76146113-7607c800-6090-11ea-8c97-df4f96a82529.png)

**Comment by Aceship** [comment]
both bug should be fixed now
