### ISSUE TITLE
suggestion: advanced operator filter?

### ISSUE THREAD

**Issue by Min-Lu** [Aceship/AN-EN-Tags#25]
hey so i’ve been using this site for awhile now and it’s really helpful, but i think an advanced filter when browsing operator info could be useful when looking for operators that do certain things. 

like filtering by traits, tags, skill type (such as sp charge, activation, etc). even an ascending/descending sort by stats/dpcost could also be nice.

**Comment by Aceship** [comment]
Might try making it later, currently trying to make map preview/plan first

**Comment by arthus-leroy** [comment]
Can do this one if you don't mind @Aceship . Could you make a list of all the filtering you want to add @Min-Lu ?

**Comment by Min-Lu** [comment]
Sure @arthus-leroy 

1. filtering by traits. Basically the “subclasses” in each class. If I wanted to see all the medics with the trait “Heal up to 3 friendly units at once” aka all the AOE medics, it would be nice to have a filter instead of having to click through every medic and check whether or not they have this trait. 

2. you could also possibly filter by the “tags” every operator has. for example Siege has “DP-Recovery” and “DPS”, Nightmare has “DPS” “Healing” and “Slow”, we could also implement a filter by these tags too? 

3. being able to sort your search by attack, defense, hp, and dp cost. If I wanted to know out of every guard, or even every guard with the “ranged trait” who has the lowest and who has the highest dp cost this might be nice? 

4. MAYBE a filter by each operators affiliation (ex: penguin logistics, rhodes island, ursus). I know this would’ve been useful for me when I was trying to figure out who I was missing to complete “The Abyssal Hunters” in the trust overview. 

5. lastly is a filter by skill type. Their sp charge type and skill activation, so if I was looking for operators that had a skill that would gain sp from Chen’s talent, this could be useful? 

If anyone else wants to add on any other ideas that would be great, these are just things that I thought of myself.

**Comment by Aceship** [comment]
> 
> 
> Can do this one if you don't mind @Aceship . Could you make a list of all the filtering you want to add @Min-Lu ?

no problem 👍

**Comment by arthus-leroy** [comment]
@Min-Lu Would you rather have an exclusive search or a non-exclusive one ?
* The exclusive filters the operators that don't match all the criteria (meaning you can't combine 2 classes or 2 factions)
* The non-exclusive filter the operator that don't match any criterion

NOTE: The non-exclusive can quickly become quite overloaded as more criteria are checked

Or, perhaps give the user the choice over one or the other ?

**Comment by arthus-leroy** [comment]
Report on progress (will be updated as progress happen) :
0 - Previous behavior (DONE)
1 - Subclasses (TODO, would be nice to have custom icons for each of them)
2 - Tags (WIP for tomorrow)
3 - Sorting (WIP for tomorrow)
4 - Factions (DONE)
5 - Skill type (TODO)

**Comment by Min-Lu** [comment]
@arthus-leroy Exclusive probably...? 

I can’t really think of a situation that’s not super specific where I’d need to use a non-exclusive filter.

though I guess it’s also possible to have a non-exclusive search but also have a limit on the number of filters you can select to prevent overloading.

**Comment by arthus-leroy** [comment]
@Min-Lu @Aceship I would like to have your opinion on the stat sorting.
We have up to 3 cases : E0, E1, E2. Each one have lvl1 and lvl max. This makes 6 states that contain stats. We can *merge* 2 states as (usually) E0 max ≃ E1 lvl1 and E1 max ≃ E2 lvl1. This still makes up to 4 states from which we must choose a value.
Also another problem arise : between 2 operators of different rarity, there is a gap of level (and hence stats) at E1 max and at E2 max. This means that sorting by stats can lead to a sort by rarity, unless E0 lvl1 is chosen.
The easy answer would be to choose E0 lvl1, but I’m not sure if it’s the best solution.

What would, for you, be the best (or one of the best) way to sort by stats ?

**Comment by Aceship** [comment]
personally it would be better with maxed stats (e2 90 for 6*, e2 80 for 5* and so)
since usually people wants to see which operator has the highest stats, so they can see who to invest 

~but you can also do something like custom filter like choosing either elite 0-2 , level 0-90 eitherway~

**Comment by Min-Lu** [comment]
@arthus-leroy I agree with Aceship, it’s probably best to just default it to the max level/elite for each operator

**Comment by Aceship** [comment]
@Min-Lu The feature is up online now, check if there's something missing or if you got some more idea

**Comment by Min-Lu** [comment]
It works great! My only concern is on my both my PC and mobile phone the Class icons look smushed/stretched.
![F345F660-D947-4314-8361-4BE5307B97AE](https://user-images.githubusercontent.com/62037634/77576008-c6619100-6eaa-11ea-8584-4bdc30f55bf1.jpeg)

I took a quick screenshot from my iphone 7+, but it looks the same way on my macbook air, not sure how it looks for android/windows users though.

**Comment by arthus-leroy** [comment]
Can confirm it misbehaves in iOS 13, but works on Android (9), Windows (10) and Linux (Manjaro).
And it's not squished per say, it's more like the height not being set (which is true btw). It must be an Apple only settings, however it should be possible to deal with it just by adding height="40" to the img tags.
@Aceship I let you deal with it (won't do another PR just for that). A simple replace should do the trick (no more than 5 mins). If it doesn't... meh.

**Comment by Aceship** [comment]
yeah can see that happen , btw it should be fixed around minutes after newest push

**Comment by arthus-leroy** [comment]
Yes, fixed it

**Comment by Aceship** [comment]
okay everything about this should be done for now , closing it
