### ISSUE TITLE
Hellagurs skills display wrong in RIIC

### ISSUE THREAD

**Issue by TuroKK007** [Aceship/AN-EN-Tags#32]
I just noticed that there is something wrong with how Hellagurs skills are displayed in the RIIC section.
If I select the Workshop skill in RIIC he shows up, but without the Workshop skill.

RIIC section (https://aceship.github.io/AN-EN-Tags/akriic.html)
![Hellagurs skills RIIC 2](https://user-images.githubusercontent.com/62994622/78134992-5a8aa580-7421-11ea-8b1f-d273ad7d129b.png)

Operator section (https://aceship.github.io/AN-EN-Tags/akhrchars.html?opname=Hellagur)
![Hellagurs skills RIIC 1](https://user-images.githubusercontent.com/62994622/78134989-58c0e200-7421-11ea-95ad-bc7e4d8d6d9f.png)

PS: Thx for the hard work on an awesome Tool

**Comment by Aceship** [comment]
yeah the riic page only shows 2 of their skill ~(kinda known bug since hellagur appears and other with more than 2 skill appears)~ but haven't got time ~and motivation~ to fix it 

probably need redesign entire page instead
