### ISSUE TITLE
Gadget -> Device

### ISSUE THREAD

**Issue by Renari** [Aceship/AN-EN-Tags#4]
https://github.com/Aceship/AN-EN-Tags/blob/master/json/akmaterial.json#L263

This item is called `Device` in-game. I'm not sure if the other `Gadgets` are called the same.

**Comment by Aceship** [comment]
![image](https://user-images.githubusercontent.com/5337323/73069006-31a8da00-3edf-11ea-9c5f-062dbe29ab18.png)
technically it is all gadget in english translation, currently it still use community translation for most of the materials
