### ISSUE TITLE
Hellagur's skills in Aceship are translated misleadingly

### ISSUE THREAD

**Issue by philipzloh** [Aceship/AN-EN-Tags#50]
This isn't just an issue about the official translation using different terms -- the problem actually is Aceship currently uses a string for Skill 2 that the official game uses for Skill 1.

### Aceship
![image](https://user-images.githubusercontent.com/836760/84079835-27165980-aa16-11ea-90a1-2fccdf38fcea.png)
![image](https://user-images.githubusercontent.com/836760/84079844-2d0c3a80-aa16-11ea-86cf-8b39648c7f1c.png)
![image](https://user-images.githubusercontent.com/836760/84079854-31385800-aa16-11ea-88a3-4139c28fbad5.png)

### Official client
![20200608_205529000_iOS](https://user-images.githubusercontent.com/836760/84080976-11099880-aa18-11ea-893c-f23199cc31a6.png)

**Comment by Aceship** [comment]
lemme ask the translator first, because if its just changed here, it still gonna be that again in next tl update

**Comment by Aceship** [comment]
so, according to jet (translator), the official en translation on first skill is actually wrong, but his s2 is translation wrong, 
its supposed to be New Moon/Half Moon/Full Moon instead, i'll push the right one in a minute 

thanks for the report
