### ISSUE TITLE
[Suggestion] Add token information

### ISSUE THREAD

**Issue by tokataka** [Aceship/AN-EN-Tags#64]
What about adding information of tokens of operators? (e.g. Phantom, Weedy, etc)
It would be useful for building tactics.

**Comment by Aceship** [comment]
uh which tokens ?
is it this one 
![image](https://user-images.githubusercontent.com/5337323/87852409-f508e900-c92b-11ea-813b-4734c1406a3a.png)

or this one 
![image](https://user-images.githubusercontent.com/5337323/87852415-00f4ab00-c92c-11ea-910e-6275cbbc74f8.png)

**Comment by tokataka** [comment]
I mean info of tokens like shadow of Phantom; stats and some traits.

**Comment by tokataka** [comment]
some changes for test purpose
tokataka/AN-EN-Tags@feb4d08412fe242887e8798fcb184fbfdff7e0b4

![image](https://user-images.githubusercontent.com/22884343/87862806-fcada980-c98e-11ea-8dac-c7bb33d8d91d.png)

It needs additional styles but works fine

However following issue should be fixed: Magellan's tokens swap by choosing skill and they have totally different stats and range.

You can check it here: https://tokataka.github.io/AN-EN-Tags/akhrchars.html

**Comment by Aceship** [comment]
ah you meant the summon, i have some idea about it , but never got time to actually make it 
i'll check it when i got time

**Comment by tokataka** [comment]
thx
