### ISSUE TITLE
Recruitment calculator bug

### ISSUE THREAD

**Issue by Mars132** [Aceship/AN-EN-Tags#83]
With JP server selected, choose ranged, then melee.
![image](https://user-images.githubusercontent.com/42975890/103404406-75cb4280-4b64-11eb-8932-c8314d181f99.png)

**Comment by Mars132** [comment]
Also, clicking on Greyy brings up Chen.

**Comment by Aceship** [comment]
should be fixed in few minutes

**Comment by Mars132** [comment]
Looks clean so far, thanks.
