### ISSUE TITLE
Can you add this 2 material to the calculator?

### ISSUE THREAD

**Issue by taeyeon9718** [Aceship/AN-EN-Tags#92]
![mat](https://user-images.githubusercontent.com/42028675/117336786-28befa80-aecf-11eb-9e4f-a327c5dd7d6d.jpg)

Much appreciated if possible! thank you!

**Comment by SoupTomato** [comment]
after the realease of Mudrock and Rosmontis, they introduce new item. And its still missing this 2 item.

**Comment by Aceship** [comment]
should be fixed now
