### ISSUE TITLE
[Bug] Exia has the senior operator tag

### ISSUE THREAD

**Issue by xneswii** [Aceship/AN-EN-Tags#94]
Exusiai has the senior operator tag if you click on her in the recruitment calculator, but doesn't show up under the senior operator tag filter. (Plus she can't be pulled from a senior operator tag, as far as I know)
![exia tag bug](https://user-images.githubusercontent.com/84540526/119036902-4e440d80-b97f-11eb-9d42-4ef2901d6d4f.PNG)

**Comment by Aceship** [comment]
fixed now
